import json

# Minimal set of categories and words to expand to ~1000
# I will use a simple multiplication technique for demonstration if I cant fit 1000 distinct strings in this script
# But I will try to fit as many distinct ones as possible.

categories = {
    "Animals": {
        "en": ["Lion", "Tiger", "Bear", "Elephant", "Giraffe", "Zebra", "Monkey", "Kangaroo", "Koala", "Penguin", "Dolphin", "Whale", "Shark", "Eagle", "Hawk", "Owl", "Parrot", "Dog", "Cat", "Mouse", "Rat", "Rabbit", "Fox", "Wolf", "Deer", "Moose", "Buffalo", "Cow", "Pig", "Sheep", "Goat", "Horse", "Chicken", "Duck", "Goose", "Turkey", "Swan", "Frog", "Toad", "Snake", "Lizard", "Turtle", "Crocodile", "Alligator", "Spider", "Ant", "Bee", "Butterfly", "Moth", "Beetle", "Worm", "Snail", "Crab", "Lobster", "Octopus", "Squid", "Jellyfish", "Starfish", "Seahorse", "Seal", "Walrus", "Otter", "Beaver", "Raccoon", "Skunk", "Squirrel", "Chipmunk", "Hedgehog", "Porcupine", "Bat", "Mole", "Badger", "Panda", "Gorilla", "Chimpanzee", "Orangutan", "Lemur", "Meerkat", "Hyena", "Cheetah", "Leopard", "Jaguar", "Cougar", "Lynx", "Bobcat", "Ocelot", "Camel", "Llama", "Alpaca", "Vicuna", "Gazelle", "Antelope", "Wildebeest", "Rhino", "Hippo", "Warthog", "Ostrich", "Emu", "Kiwi", "Peacock", "Flamingo", "Heron", "Stork", "Pelican", "Seagull", "Albatross", "Puffin", "Woodpecker", "Hummingbird", "Kingfisher", "Sparrow", "Robin", "Bluejay", "Cardinal", "Crow", "Raven", "Magpie", "Pigeon", "Dove", "Quail", "Pheasant", "Grouse", "Partridge", "Salmon", "Trout", "Bass", "Tuna", "Cod", "Herring", "Sardine", "Anchovy", "Catfish", "Goldfish", "Carp", "Koi", "Guppy", "Tetra", "Betta", "Angelfish", "Clownfish"],
        "es": ["León", "Tigre", "Oso", "Elefante", "Jirafa", "Cebra", "Mono", "Canguro", "Koala", "Pingüino", "Delfín", "Ballena", "Tiburón", "Águila", "Halcón", "Búho", "Loro", "Perro", "Gato", "Ratón", "Rata", "Conejo", "Zorro", "Lobo", "Ciervo", "Alce", "Búfalo", "Vaca", "Cerdo", "Oveja", "Cabra", "Caballo", "Pollo", "Pato", "Ganso", "Pavo", "Cisne", "Rana", "Sapo", "Serpiente", "Lagarto", "Tortuga", "Cocodrilo", "Caimán", "Araña", "Hormiga", "Abeja", "Mariposa", "Polilla", "Escarabajo", "Gusano", "Caracol", "Cangrejo", "Langosta", "Pulpo", "Calamar", "Medusa", "Estrella de mar", "Caballito de mar", "Foca", "Morsa", "Nutria", "Castor", "Mapache", "Ardilla", "Puercoespín", "Murciélago", "Topo", "Tejón", "Panda", "Gorila", "Chimpancé", "Orangután", "Hiena", "Leopardo", "Jaguar", "Puma", "Gato montés", "Camello", "Llama", "Alpaca", "Vicuña", "Gacela", "Antílope", "Rinoceronte", "Hipopótamo", "Jabalí", "Avestruz", "Pavo real", "Flamenco", "Pelícano", "Gaviota", "Pájaro carpintero", "Colibrí", "Gorrión", "Cardenal", "Cuervo", "Paloma", "Codorniz", "Perdiz", "Salmón", "Trucha", "Bajo", "Atún", "Bacalao", "Sardina", "Anchoa", "Bagre", "Pez dorado", "Carpa"]
    },
    "Food": {
        "en": ["Pizza", "Burger", "Sushi", "Taco", "Pasta", "Salad", "Steak", "Chicken", "Fish", "Rice", "Bread", "Cheese", "Egg", "Milk", "Yogurt", "Butter", "Ice Cream", "Cake", "Cookie", "Pie", "Donut", "Muffin", "Bagel", "Toast", "Sandwich", "Soup", "Stew", "Curry", "Noodle", "Dumpling", "Spring Roll", "Samosa", "Burrito", "Quesadilla", "Enchilada", "Fajita", "Nachos", "Chips", "Fries", "Onion Rings", "Hot Dog", "Sausage", "Bacon", "Ham", "Pork", "Beef", "Lamb", "Veal", "Venison", "Duck", "Turkey", "Salmon", "Tuna", "Shrimp", "Crab", "Lobster", "Clam", "Oyster", "Mussel", "Scallop", "Octopus", "Squid", "Apple", "Banana", "Orange", "Grape", "Strawberry", "Blueberry", "Raspberry", "Blackberry", "Cherry", "Peach", "Pear", "Plum", "Apricot", "Nectarine", "Mango", "Pineapple", "Papaya", "Kiwi", "Melon", "Watermelon", "Lemon", "Lime", "Grapefruit", "Avocado", "Tomato", "Potato", "Carrot", "Onion", "Garlic", "Ginger", "Pepper", "Broccoli", "Cauliflower", "Cabbage", "Lettuce", "Spinach", "Kale", "Celery", "Cucumber", "Zucchini", "Eggplant", "Mushroom", "Corn", "Peas", "Beans", "Lentils", "Chickpeas", "Soybeans", "Tofu", "Tempeh", "Seitan", "Quinoa", "Oats", "Barley", "Wheat", "Rye", "Rice", "Millet", "Sorghum", "Buckwheat", "Amaranth", "Teff", "Chia", "Flax", "Hemp", "Sesame", "Sunflower", "Pumpkin", "Walnut", "Almond", "Cashew", "Pistachio", "Pecan", "Hazelnut", "Macadamia", "Brazil Nut", "Peanut", "Coconut", "Chocolate", "Vanilla", "Cinnamon", "Nutmeg", "Clove", "Ginger", "Turmeric", "Cumin", "Coriander", "Cardamom", "Saffron", "Paprika", "Chili", "Pepper", "Salt", "Sugar", "Honey", "Syrup", "Jam", "Jelly", "Marmalade", "Peanut Butter", "Butter", "Cheese", "Yogurt", "Cream", "Milk", "Tea", "Coffee", "Juice", "Soda", "Water", "Beer", "Wine", "Whiskey", "Vodka", "Rum", "Gin", "Tequila", "Brandy", "Cider", "Champagne", "Cocktail", "Smoothie", "Milkshake"],
        "es": ["Pizza", "Hamburguesa", "Sushi", "Taco", "Pasta", "Ensalada", "Pollo", "Pescado", "Arroz", "Pan", "Queso", "Huevo", "Leche", "Yogur", "Manteca", "Helado", "Pastel", "Galleta", "Tarta", "Magdalena", "Bagel", "Tostada", "Sándwich", "Sopa", "Estofado", "Curry", "Fideos", "Rollito primavera", "Burrito", "Quesadilla", "Fajita", "Nachos", "Papas fritas", "Aros de cebolla", "Salchicha", "Bacon", "Jamón", "Cerdo", "Ternera", "Cordero", "Venado", "Pato", "Pavo", "Salmón", "Atún", "Camarón", "Cangrejo", "Langosta", "Almeja", "Ostra", "Mejillón", "Pulpo", "Calamar", "Manzana", "Banana", "Naranja", "Uva", "Frutilla", "Frambuesa", "Cereza", "Pera", "Ciruela", "Mango", "Piña", "Papaya", "Kiwi", "Melón", "Sandía", "Limón", "Lima", "Pomelo", "Palta", "Tomate", "Papa", "Zanahoria", "Cebolla", "Ajo", "Jengibre", "Morrón", "Brócoli", "Coliflor", "Repollo", "Lechuga", "Espinaca", "Apio", "Pepino", "Berenjena", "Champiñón", "Maíz", "Lentejas", "Garbanzos", "Soja", "Tofu", "Quinoa", "Avena", "Cebada", "Trigo", "Centeno", "Arroz", "Trigo sarraceno", "Sésamo", "Girasol", "Calabaza", "Nuez", "Almendra", "Pistacho", "Avellana", "Maní", "Coco", "Chocolate", "Vainilla", "Canela", "Nuez moscada", "Clavo", "Jengibre", "Cúrcuma", "Comino", "Cilantro", "Cardamomo", "Azafrán", "Pimentón", "Pimienta", "Sal", "Azúcar", "Miel", "Jarabe", "Mermelada", "Jalea", "Mermelada", "Queso", "Yogur", "Crema", "Leche", "Té", "Café", "Jugo", "Agua", "Cerveza", "Vino", "Whisky", "Vodka", "Ron", "Tequila", "Sidra"]
    },
    "Jobs": {
        "en": ["Doctor", "Teacher", "Engineer", "Nurse", "Police", "Firefighter", "Lawyer", "Accountant", "Architect", "Artist", "Musician", "Actor", "Writer", "Journalist", "Chef", "Waiter", "Bartender", "Pilot", "Driver", "Mechanic", "Electrician", "Plumber", "Carpenter", "Farmer", "Fisherman", "Soldier", "Scientist", "Researcher", "Professor", "Student", "Librarian", "Politician", "Judge", "Priest", "Monk", "Nun", "Pope", "King", "Queen", "Prince", "Princess", "President", "Minister", "Secretary", "Clerk", "Receptionist", "Manager", "Director", "CEO", "Entrepreneur", "Investor", "Banker", "Broker", "Agent", "Consultant", "Advisor", "Coach", "Trainer", "Athlete", "Referee", "Umpire", "Guard", "Security", "Detective", "Inspector", "Spy", "Hacker", "Programmer", "Developer", "Designer", "Photographer", "Editor", "Publisher", "Translator", "Interpreter", "Guide", "Host", "Steward", "Cleaner", "Janitor", "Gardener", "Florist", "Baker", "Butcher", "Barber", "Hairdresser", "Tailor", "Shoemaker", "Jeweler", "Watchmaker", "Blacksmith", "Miner", "Oilman", "Sailor", "Captain", "Pirate", "Astronaut", "Alien", "Robot", "Cyborg", "Ghost", "Vampire", "Werewolf", "Zombie", "Witch", "Wizard", "Fairy", "Elf", "Dwarf", "Giant", "Dragon", "Monster"],
        "es": ["Médico", "Maestro", "Ingeniero", "Enfermera", "Policía", "Bombero", "Abogado", "Contador", "Arquitecto", "Artista", "Músico", "Actor", "Escritor", "Periodista", "Chef", "Camarero", "Piloto", "Conductor", "Mecánico", "Electricista", "Plomero", "Carpintero", "Granjero", "Pescador", "Soldado", "Científico", "Investigador", "Profesor", "Estudiante", "Bibliotecario", "Político", "Juez", "Sacerdote", "Monje", "Monja", "Papa", "Rey", "Reina", "Príncipe", "Princesa", "Presidente", "Ministro", "Secretario", "Empleado", "Recepcionista", "Gerente", "Director", "Emprendedor", "Inversor", "Banquero", "Agente", "Consultor", "Asesor", "Entrenador", "Atleta", "Árbitro", "Guardia", "Seguridad", "Detective", "Inspector", "Espía", "Hacker", "Programador", "Desarrollador", "Diseñador", "Fotógrafo", "Editor", "Traductor", "Intérprete", "Guía", "Anfitrión", "Auxiliar", "Limpiador", "Jardinero", "Florista", "Panadero", "Carnicero", "Barbero", "Peluquero", "Sastre", "Zapatero", "Joyero", "Relojero", "Herrero", "Minero", "Marinero", "Capitán", "Pirata", "Astronauta", "Extraterrestre", "Robot", "Fantasma", "Vampiro", "Hombre lobo", "Zombi", "Bruja", "Mago", "Hada", "Elfo", "Enano", "Gigante", "Dragón", "Monstruo"]
    },
     "Objects": {
        "en": ["Table", "Chair", "Sofa", "Bed", "Desk", "Lamp", "Clock", "Mirror", "Rug", "Curtain", "Pillow", "Blanket", "Towel", "Soap", "Shampoo", "Toothbrush", "Toothpaste", "Comb", "Brush", "Razor", "Perfume", "Makeup", "Phone", "Computer", "Laptop", "Tablet", "Camera", "TV", "Radio", "Speaker", "Headphones", "Charger", "Cable", "Battery", "Book", "Notebook", "Pen", "Pencil", "Eraser", "Ruler", "Scissors", "Glue", "Tape", "Stapler", "Paper", "Envelope", "Stamp", "Card", "Letter", "Box", "Bag", "Backpack", "Purse", "Wallet", "Key", "Lock", "Door", "Window", "Wall", "Floor", "Ceiling", "Roof", "Stairs", "Elevator", "Escalator", "Car", "Bus", "Train", "Plane", "Boat", "Bike", "Motorcycle", "Scooter", "Skateboard", "Helmet", "Seatbelt", "Wheel", "Tire", "Engine", "Brake", "Clutch", "Gear", "Gas", "Oil", "Water", "Air", "Fire", "Earth", "Wood", "Metal", "Plastic", "Glass", "Stone", "Brick", "Concrete", "Asphalt", "Sand", "Mud", "Dirt", "Dust", "Smoke", "Steam", "Ice", "Snow", "Rain", "Cloud", "Sun", "Moon", "Star", "Planet", "Comet", "Asteroid", "Galaxy", "Universe", "Space", "Time", "Light", "Shadow", "Color", "Sound", "Music", "Noise", "Voice", "Silence", "Smell", "Taste", "Touch", "Pain", "Pleasure", "Love", "Hate", "Joy", "Sadness", "Anger", "Fear", "Hope", "Dream", "Idea", "Memory", "Thought", "Mind", "Soul", "Spirit", "Life", "Death", "God", "Devil", "Angel", "Demon", "Heaven", "Hell", "Paradise", "Purgatory", "Limbo", "Void", "Nothing", "Everything", "Something", "Anything"],
        "es": ["Mesa", "Silla", "Sillón", "Cama", "Escritorio", "Lámpara", "Reloj", "Espejo", "Alfombra", "Cortina", "Almohada", "Manta", "Toalla", "Jabón", "Shampoo", "Cepillo de dientes", "Dentífrico", "Peine", "Cepillo", "Perfume", "Maquillaje", "Teléfono", "Computadora", "Notebook", "Tablet", "Cámara", "TV", "Radio", "Parlante", "Auriculares", "Cargador", "Cable", "Batería", "Libro", "Cuaderno", "Lapicera", "Lápiz", "Borrador", "Regla", "Tijera", "Pegamento", "Cinta", "Papel", "Sobre", "Sello", "Tarjeta", "Carta", "Caja", "Bolsa", "Mochila", "Bolso", "Cartera", "Llave", "Cerradura", "Puerta", "Ventana", "Pared", "Piso", "Techo", "Escaleras", "Ascensor", "Escalera mecánica", "Coche", "Autobús", "Tren", "Avión", "Barco", "Bicicleta", "Moto", "Scooter", "Monopatín", "Casco", "Cinturón de seguridad", "Rueda", "Motor", "Freno", "Embrague", "Engranaje", "Gas", "Aceite", "Agua", "Aire", "Fuego", "Tierra", "Madera", "Metal", "Plástico", "Vidrio", "Piedra", "Ladrillo", "Hormigón", "Asfalto", "Arena", "Barro", "Suciedad", "Polvo", "Humo", "Vapor", "Hielo", "Nieve", "Lluvia", "Nube", "Sol", "Luna", "Estrella", "Planeta", "Cometa", "Asteroide", "Galaxia", "Universo", "Espacio", "Tiempo", "Luz", "Sombra", "Sonido", "Música", "Ruido", "Voz", "Silencio", "Olor", "Sabor", "Tacto", "Dolor", "Placer", "Amor", "Odio", "Alegría", "Tristeza", "Ira", "Miedo", "Esperanza", "Sueño", "Idea", "Recuerdo", "Pensamiento", "Mente", "Alma", "Espíritu", "Vida", "Muerte", "Dios", "Diablo", "Ángel", "Demonio", "Cielo", "Infierno", "Paraíso", "Purgatorio", "Limbo", "Vacío"]
    },
    "Places": {
        "en": ["Home", "School", "Work", "Office", "Hospital", "Clinic", "Pharmacy", "Bank", "Post Office", "Library", "Museum", "Cinema", "Theater", "Stadium", "Gym", "Park", "Zoo", "Beach", "Pool", "Lake", "River", "Forest", "Mountain", "Desert", "City", "Town", "Village", "Farm", "Factory", "Shop", "Store", "Market", "Mall", "Restaurant", "Cafe", "Bar", "Pub", "Club", "Hotel", "Motel", "Hostel", "Inn", "Resort", "Camp", "Tent", "Cabin", "House", "Apartment", "Condo", "Castle", "Palace", "Temple", "Church", "Mosque", "Synagogue", "Shrine", "Altar", "Tomb", "Grave", "Cemetery", "Morgue", "Prison", "Jail", "Police Station", "Fire Station", "Court", "Embassy", "Consulate", "Airport", "Station", "Port", "Harbor", "Dock", "Pier", "Bridge", "Tunnel", "Road", "Street", "Lane", "Avenue", "Boulevard", "Highway", "Freeway", "Path", "Trail", "Track", "Field", "Meadow", "Garden", "Yard", "Patio", "Balcony", "Terrace", "Roof", "Attic", "Basement", "Garage", "Kitchen", "Living Room", "Bedroom", "Bathroom", "Toilet", "Hall", "Corridor", "Closet", "Pantry", "Laundry", "Gym", "Spa", "Sauna", "Barber Shop", "Beauty Salon", "Hardware Store", "Bookstore", "Bakery", "Butcher Shop", "Grocery Store", "Supermarket", "Department Store", "Shoe Store", "Clothing Store", "Jewelry Store", "Toy Store", "Pet Store", "Flower Shop"],
        "es": ["Hogar", "Escuela", "Trabajo", "Oficina", "Hospital", "Clínica", "Farmacia", "Banco", "Biblioteca", "Museo", "Cine", "Teatro", "Estadio", "Gimnasio", "Parque", "Zoológico", "Playa", "Lago", "Río", "Bosque", "Montaña", "Desierto", "Ciudad", "Pueblo", "Aldea", "Granja", "Fábrica", "Mercado", "Shopping", "Restaurante", "Café", "Bar", "Club", "Hotel", "Motel", "Posada", "Campamento", "Carpa", "Cabaña", "Casa", "Departamento", "Castillo", "Palacio", "Templo", "Iglesia", "Mezquita", "Sinagoga", "Santuario", "Altar", "Tumba", "Cementerio", "Morgue", "Cárcel", "Estación de bomberos", "Tribunal", "Embajada", "Consulado", "Aeropuerto", "Puerto", "Muelle", "Puente", "Túnel", "Ruta", "Calle", "Carril", "Avenida", "Autopista", "Camino", "Pista", "Campo", "Jardín", "Patio", "Balcón", "Terraza", "Techo", "Sótano", "Garaje", "Cocina", "Dormitorio", "Baño", "Pasillo", "Corredor", "Armario", "Lavandería", "Gimnasio", "Spa", "Sauna", "Barbería", "Ferretería", "Librería", "Panadería", "Carnicería", "Supermercado", "Zapatería", "Joyería", "Juguetería", "Florería"]
    }
}

print("import type { WordPackItem } from '../types';")
print("")
print("const defaultWords: WordPackItem[] = [")

count = 0
for category, langs in categories.items():
    for lang, words in langs.items():
        for word in words:
            # Enforce single word constraint
            if ' ' in word or '-' in word:
                continue

            # Ensure capitalized
            w_clean = word.title()

            count += 1
            print(f"    {{ id: '{count}', word: '{w_clean}', category: '{category}', language: '{lang}', difficulty: 'easy' }},")

print("];")
print("")
print("export function getRandomWord(language: 'en' | 'es'): string {")
print("    const langWords = defaultWords.filter(w => w.language === language);")
print("    if (langWords.length === 0) return 'Word';")
print("    const randomIndex = Math.floor(Math.random() * langWords.length);")
print("    return langWords[randomIndex].word;")
print("}")
